#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

- name: Set access token
  when: access_token_env is not defined
  block:
    - name: Generate access token
      ansible.builtin.shell: sudo bash -lc 'gen_access_token'
      register: access_token_result
      changed_when: false

    - name: Set access token as environment variable
      ansible.builtin.set_fact:
        access_token_env: "{{ access_token_result.stdout }}"

- name: Discover nodes
  environment:
    "{{ cluster_name | capitalize }}_ACCESS_TOKEN": "{{ access_token_env }}"
  block:
    - name: Create ochami nodes directory
      ansible.builtin.file:
        path: '{{ ochami_work_dir }}/nodes'
        state: directory
        mode: '{{ file_perm_rwx }}'

    - name: Drop ochami nodes.yaml
      ansible.builtin.template:
        src: nodes.yaml.j2
        dest: '{{ ochami_work_dir }}/nodes/nodes.yaml'
        mode: '{{ file_perm_rw }}'

    - name: Discovery ochami nodes
      ansible.builtin.shell: |
        ochami discover static -f yaml -d @{{ ochami_work_dir }}/nodes/nodes.yaml
      changed_when: true

    - name: Verify node created in smd
      ansible.builtin.shell: |
        ochami smd component get | jq '.Components[] | select(.Type == "Node")'
      changed_when: true
      register: openchami_smd_status

    - name: Openchami smd status output
      ansible.builtin.debug:
        msg: "{{ openchami_smd_status.stdout_lines }}"
