#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Get latest openchami response
  ansible.builtin.uri:
    url: "{{ openchami_api_url }}"
    return_content: true
  register: openchami_release_response

- name: Extract openchami RPM download URL
  ansible.builtin.set_fact:
    openchami_rpm_url: "{{ openchami_release_response.content | from_json | json_query('assets[?ends_with(name, `.rpm`)].browser_download_url') | first }}"
    openchami_rpm_name: "{{ openchami_release_response.content | from_json | json_query('assets[?ends_with(name, `.rpm`)].name') | first }}"

- name: Download the openchami RPM file
  ansible.builtin.get_url:
    url: "{{ openchami_rpm_url }}"
    dest: "{{ ochami_work_dir }}/{{ openchami_rpm_name }}"

- name: Install the openchami
  ansible.builtin.dnf:
    name: "{{ ochami_work_dir }}/{{ openchami_rpm_name }}"
    state: present
    disable_gpg_check: true

- name: Update openchami certificates
  ansible.builtin.shell: |
    sudo openchami-certificate-update update {{ cluster_name }}.{{ cluster_domain }}
  changed_when: true

- name: Start the openchami service
  ansible.builtin.systemd:
    name: openchami.target
    state: started
    enabled: true
    daemon_reload: true

- name: Get ochami client respone
  ansible.builtin.uri:
    url: "{{ ochami_client_api_url }}"
    return_content: true
  register: ochami_client_release_response

- name: Extract ochami RPM download URL
  ansible.builtin.set_fact:
    ochami_client_rpm_url: "{{ ochami_client_release_response.content | from_json | json_query('assets[?ends_with(name, `amd64.rpm`)].browser_download_url') | first }}"
    ochami_client_rpm_name: "{{ ochami_client_release_response.content | from_json | json_query('assets[?ends_with(name, `amd64.rpm`)].name') | first }}"

- name: Download the ochami client RPM file
  ansible.builtin.get_url:
    url: "{{ ochami_client_rpm_url }}"
    dest: "{{ ochami_work_dir }}/{{ ochami_client_rpm_name }}"

- name: Install ochami CLI
  ansible.builtin.dnf:
    name: "{{ ochami_work_dir }}/{{ ochami_client_rpm_name }}"
    state: present
    disable_gpg_check: true

- name: Configure ochami CLI
  ansible.builtin.template:
    src: ochami/config.yaml.j2
    dest: '{{ ochami_dir }}/config.yaml'

# - name: Drop ochami nodes.yaml
#   ansible.builtin.template:
#     src: ochami/nodes.yaml.j2
#     dest: '{{ ochami_dir }}/nodes.yaml'

# - name: Drop ochami groups.yaml
#   template:
#     src: ochami/groups.yaml.j2
#     dest: '{{ ochami_dir }}/groups.yaml'
