- name: Import packages task
  ansible.builtin.import_tasks: packages.yaml

- name: Import configs task
  ansible.builtin.import_tasks: configs.yaml

- name: Import hosts task
  ansible.builtin.import_tasks: hosts.yaml

- name: Import minio task
  ansible.builtin.import_tasks: minio.yaml

- name: Import registry task
  ansible.builtin.import_tasks: registry.yaml

- name: Import coredhcp task
  ansible.builtin.import_tasks: coredhcp.yaml

- name: Import ochami task
  ansible.builtin.import_tasks: ochami.yaml

- name: Import verify task
  ansible.builtin.import_tasks: verify.yaml